### ISSUE TITLE
Install on Mac El Capitan with PHP 7

### ISSUE THREAD

**Issue by meet-bhagdev** [radsectors/sqlshim#10]
I am having trouble getting sqlshim to work on my Mac. I am using PHP 7. I have also installed FreeTDS and confirmed it works. How do I setup sqlshim and FreeTDS to work together on Mac?

**Comment by meeshypeeshy** [comment]
We've recently got this working without unixODBC and FreeTDS on a Mac. The old Mac-specific instructions in the wiki were always lengthy, complex, and troublesome. We just haven't had the chance to write up new instructions.
See if you can find and install a PHP module named "dblib", "sybase", or possibly "mssql." Basically, follow the Linux instructions where possible.

**Comment by meet-bhagdev** [comment]
Oh sweet! That's awesome :) Where would i find the Linux instructions?

**Comment by meeshypeeshy** [comment]
Ah, sorry. I assumed you were referring to the Mac instructions in the wiki.
You can find the instructions there https://github.com/radsectors/sqlshim/wiki

**Comment by meeshypeeshy** [comment]
Did you ever make any progress with this?

**Comment by meeshypeeshy** [comment]
no news is good news.
