### ISSUE TITLE
Doctrine - SQL Server error occurred but no error message was retrieved from driver.

### ISSUE THREAD

**Issue by iluuu1994** [radsectors/sqlshim#11]
I'm trying to connect to our Sql Server from my Mac using sqlshim.

Doctrine gives me the following exception which is not helpful at all:

```
object(Doctrine\DBAL\Driver\SQLSrv\SQLSrvException)#279 (7) {
  ["message":protected]=>
  string(73) "SQL Server error occurred but no error message was retrieved from driver."
  ...
```

The specified driver for Doctrine is `sqlsrv`. I've tested the credentials using the **SQLPro for MSSQL** application and they are indeed correct. What can I do?

Thanks for your help!

**Comment by iluuu1994** [comment]
I didn't install **pdo_dblib** which I know fixed. It "works". There seem to be various issues with Doctrine unfortunately. Closing this for now.

**Comment by meeshypeeshy** [comment]
Happy to help! :D
