### ISSUE TITLE
value type binding

### ISSUE THREAD

**Issue by dinglidingli** [radsectors/sqlshim#12]
Hello, 

I was wondering how we can go about binding parameters / values as inputs / outputs with this shim. This also encompasses manual definition of the value's SQL type.

Passing the params to sqlsrv_query (documented on http://php.net/manual/en/function.sqlsrv-query.php) in a format like:
```
[
  ['value1', SQLSRV_PARAM_IN],
  ['value2', SQLSRV_PARAM_INOUT],
  ['value3', SQLSRV_PARAM_OUT],
]
```

results in an array to string conversion error (likely due to the shim expecting parameters to not be arrays)

**Comment by meeshypeeshy** [comment]
Hi!
Yeah, I haven't had the opportunity to build support for this method particular parameter format. But I could probably whip up some superficial support in the mean time. That would at least workaround the string conversion error.

**Comment by meeshypeeshy** [comment]
Just pushed an update last night. Let me know if that gets rid of the string conversion error.

**Comment by meeshypeeshy** [comment]
@chrisdingli i'm assuming this worked out for you. by all means, reopen if not. thanks for the feedback!
