### ISSUE TITLE
Interpretation of Strings to DateTime

### ISSUE THREAD

**Issue by leykevin** [radsectors/sqlshim#14]
if i have a column in SQL with a value like xxx-yy-zz. I received the folowing error:
[Tue Apr 04 15:02:05.023778 2017] [:error] [pid 8562] [client xxxx:57350] PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (2126-82-04) at position 6 (2): Unexpected character in /var/www/xxx/sqlshim.php:297\nStack trace:\n#0 /var/www/xxx/sqlshim.php(297): DateTime->__construct('2126-82-04')\n#1 /var/www/xxx/sqlshim.php(269): radsectors\\sqlshim::typifyField('2126-82-04')\n#2 /var/www/xxx/sqlshim.php(617): radsectors\\sqlshim::typifyRow(Array)\n#3 /var/www/xxx/globals.php(275): radsectors\\sqlshim::fetch_array(Object(PDOStatement), 3, 1, 0)\n#4 /var/www/xxx/test.php(46): sqlsrv_fetch_array(Object(PDOStatement))\n#5 {main}\n  thrown in /var/www/xxx/sqlshim.php on line 297, referer: https://xxxxxxx/

If i uncomment the lines of the function i can't use real DateTime Columns where the value is like YYYY-MM-DD HH:ii:ss

I need to use both options and need help.

**Comment by meeshypeeshy** [comment]
how coincidental. @chrisdingli actually just submitted a pull request the other day with an update that should fix this issue. i requested a small adjustment to his commit, but i will get that merged in asap.

**Comment by leykevin** [comment]
It doesn't work. Same error. I mean i have sometimes data that isn't a DateTime but the value is in that format ( example 2126-82-04). It's a order Number.

**Comment by meeshypeeshy** [comment]
sorry, the update had not been made yet. but i just pushed it up. update and try again, please!

**Comment by leykevin** [comment]
I have testet now and i received another error now(Total are over 28.000 rows and about 100 rows can be only displayed):
[Thu Apr 06 17:48:49.348642 2017] [:error] [pid 26114] [client 217.247.72.177:61413] PHP Fatal error:  Uncaught Exception: DateTime::__construct(): Failed to parse time string (2126-82-04) at position 6 (2): Unexpected character in /var/www/test/vb/3rd/sqlshim.php:297\nStack trace:\n#0 /var/www/test/vb/3rd/sqlshim.php(297): DateTime->__construct('2126-82-04')\n#1 /var/www/test/vb/3rd/sqlshim.php(269): radsectors\\sqlshim::typifyField('2126-82-04')\n#2 /var/www/test/vb/3rd/sqlshim.php(617): radsectors\\sqlshim::typifyRow(Array)\n#3 /var/www/test/vb/3rd/globals.php(275): radsectors\\sqlshim::fetch_array(Object(PDOStatement), 3, 1, 0)\n#4 /var/www/test/vb/page/Produktstamm.php(46): sqlsrv_fetch_array(Object(PDOStatement))\n#5 {main}\n  thrown in /var/www/test/vb/3rd/sqlshim.php on line 297, referer: https://xxxxxxxx/test/vb/

**Comment by meeshypeeshy** [comment]
give that a try.

**Comment by meeshypeeshy** [comment]
also, just in case it isn't obvious, be sure you're downloading the latest dev code and not the latest "release" code. it looks like you're installing manually rather than with composer, so i want to make sure you're getting the right file(s).

but the only file that changed was `sqlshim.php`. so you can just download it here:
https://raw.githubusercontent.com/radsectors/sqlshim/master/src/sqlshim.php

**Comment by leykevin** [comment]
works perfect, thanks.
