### ISSUE TITLE
Blank Array ( )

### ISSUE THREAD

**Issue by archisss** [radsectors/sqlshim#16]
I'm trying to connect using sqlhim to a data base on OSX, 
I all ready install sqlhim via composer on my path for my connection but it give me the follow error  just print array() on the sqlsrv_error()

 require 'vendor/autoload.php';
	$serverName = "10.10.1.10";
	$connectionInfo = array("Database"=>"datosdb", "UID"=>"sa", "PWD"=>"PASSWORD");
	echo "Here i just print the $connectionInfo var_dump ->";
	var_dump($connectionInfo);
	echo "<br />";
	$conn = sqlsrv_connect($serverName, $connectionInfo);
	if($conn){
		echo "Connected";
	}else {
		echo "Conection faild <br />";
		die(print_r(sqlsrv_errors(), true));
	}

**Comment by meeshypeeshy** [comment]
Hi, thank you for checking out sqlshim.
~~Please clarify, what are you getting from sqlsrv_errors()? An empty array, or...?~~
Oh, sorry. I see now, it's in the subject.

**Comment by meeshypeeshy** [comment]
What version of php are you using?
Did you install mssql/sybase php module? Unfortunately, we don't have definitive instructions for installing on OS X, so you may have to figure something out on your own as our OS X testing has been quite limited.

**Comment by archisss** [comment]
This are the dependencies that i have install , i'm using php 5.6

<img width="783" alt="captura de pantalla 2018-10-12 a la s 09 00 05" src="https://user-images.githubusercontent.com/517183/46873865-528a1080-cdfd-11e8-9b47-f698cf9fd4b4.png">

if i can't used the lib i will help you to make the osx documentation
because it's really hard to setup sqlsrv dependencies to work with

**Comment by meeshypeeshy** [comment]
this may be a good starting place
http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.help.sqlanywhere.12.0.1/dbprogramming/php-unix-build.html

**Comment by meeshypeeshy** [comment]
🤷‍♀️
