### ISSUE TITLE
Character Entities on Mac

### ISSUE THREAD

**Issue by preflight** [radsectors/sqlshim#4]
On Mac, when you `json_encode` an array containing Spanish characters/entities, the operation fails silently and no output is given. Running `json_encode` on an array with no special chars works fine.

Shown below is the `print_r` output for an array containing `ó`.

```
Array
(
    [0] => Array
        (
            [workid] => 8744
            [trending] => 1
            [work_slug] => 
            [title] => Edici�n compacta NTV letra grande, DuoTono
            [title_sort] => Edici�n compacta NTV letra grande, DuoTono
```

**Comment by meeshypeeshy** [comment]
Hey @preflight, is this still an issue even on #08c1c3c42c40eb736e54c0870e0f09a706f1323a?

**Comment by meeshypeeshy** [comment]
closing because I think this issue was probably environment-related.
