### ISSUE TITLE
Incorrect link on Wiki Home to 3rd Party Lib Setup instructions

### ISSUE THREAD

**Issue by shahnhogan** [radsectors/sqlshim#7]
The link to the 3rd Party Lib Setup instructions on https://github.com/radsectors/sqlshim/wiki has an incorrect link. Correct link is: https://github.com/radsectors/sqlshim/wiki/3rd%E2%80%91party-Lib-Setup

**Comment by meeshypeeshy** [comment]
Thanks! Fixed!
