### ISSUE TITLE
Issue connecting to Azure Database

### ISSUE THREAD

**Issue by Livamyrd** [radsectors/sqlshim#9]
Hi there,

I found this library today and i'm trying to use it in my Linux webserver... But i can't manage to connect to my server.

i'm using this code:

<?php  
        require_once('../sqlshim/src/sqlshim.php');
        \RadSectors\SqlShim::init();

 $connectionInfo = array("UID" => "user@server", "pwd" => "myPassword", "Database" => "MyDB", "LoginTimeout" => 30, "Encrypt" => 1, "TrustServerCertificate" => 0);
 $serverName = "tcp:myserver.database.windows.net,1433";
 $conn = sqlsrv_connect($serverName, $connectionInfo);

```
if( $conn ) {
 echo "Connection established.<br />";
```

}else{
     echo "Connection could not be established.<br />";
     die( print_r( sqlsrv_errors(), true));
}
?>

Can you give me a connection example?

Thank you very much

**Comment by meeshypeeshy** [comment]
That should work, in theory.
Is sqlsrv_errors() actually returning anything?

My only guess at this point might be our lack of support for the **Encrypt** and **TrustServerCertificate** options.

**LoginTimeout** is also being ignored, but I'm sure that's not causing the issue. Still would be good to support, though.

**Comment by meeshypeeshy** [comment]
I'll have to do some googling and figure out what the dblib equivalent connection string options are for those.

**Comment by Livamyrd** [comment]
@radsectors Not, sqlsrv_errors() is not returning a thing. I paste the return:

Connection could not be established.<br />Array
(
)

An empty array is what i get in return. Also, i have removed the Encrypt and TrustServerCertificate parameters and i'm getting the same fail.

Do you have any working examples? It might be helpful.

Thank you very much for your quick anwser, btw :)

**Comment by dexterfichuk** [comment]
Here's what I'm using and is allowing me to connect! Make sure you've initiated sqlshim first.

```
$connectionInfo = array("UID" => "dbuser", "PWD" => "dbpassword", "Database" => "targetdb");
$connection = sqlsrv_connect("dbhostname", $connectionInfo);
```

**Comment by Livamyrd** [comment]
When you write "Make sure you've initiated sqlshim first" you mean this snippet, right?

`require_once('../sqlshim/src/sqlshim.php');
        \RadSectors\SqlShim::init();`

I mean... With your connection string i still can't connect to my database. I think i will deploy a DesktopApp with Visual Studio to provide local access to the database.

Thank you for your help & work anyway, i will stay tuned for further updates :)

**Comment by meeshypeeshy** [comment]
Sorry, things got busy at home last night.

Meant to ask: did you install **freetds** and **sybase**?
https://github.com/radsectors/sqlshim/wiki/3rd%E2%80%91party-Lib-Setup

**Comment by Livamyrd** [comment]
Hi there,

no, i didn't install these packages, because i have a 1&1 server and i don't have apt-get. Is it a MUST install?

**Comment by meeshypeeshy** [comment]
Yeah, it is definitely required.
Also, what flavor of linux is it?
So, but you do have shell access, right? Just no package manager?

**Comment by Livamyrd** [comment]
Hi there, last days were just crazy, i will check if i can access a package manager and give it a last chance.

Thx for your support!

**Comment by meeshypeeshy** [comment]
Hi @Livamyrd did you ever get this worked out? Or did you end up going with another solution?

**Comment by Livamyrd** [comment]
Hi @radsectors,

finally, i linked my Javascript with cURL in PHP to send data to a custom endpoint that i made in my Azure machine. I know is not the best way to handle it, but it works.

**Comment by meeshypeeshy** [comment]
lol I've considered solutions like that before! Thanks for trying out sqlshim!
